### ISSUE TITLE
Integrate Travis CI script for builds

### ISSUE THREAD

**Issue by brijeshshah13** [brijeshshah13/OpenCI#10]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    
### Feature Request

**Feature Description**

Integrate Travis CI script for testing the app builds.
   
**Would you like to work on the issue?**

Up for grabs.

**Comment by harshvardhan-takawale** [comment]
@brijeshshah13  I'm yet to be a bit comfortable with Travis CI, I'll try this.

**Comment by brijeshshah13** [comment]
@harshvardhan-takawale Sure. Shall I assign this to you then?
