### ISSUE TITLE
Display ProgressBar until the repos are loaded

### ISSUE THREAD

**Issue by brijeshshah13** [brijeshshah13/OpenCI#16]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    
### Feature Request

**Feature Description**

Currently, when Repositories is selected from the selected, no content is shown on the screen as the data is loading. Therefore we must display a ProgressBar until the repositories have loaded.
   
**Would you like to work on the issue?**

Up for grabs.

**Comment by Dharmik98** [comment]
@brijeshshah13  I found a useful loading bar on behalf simple progressbar .
check here:
https://github.com/race604/WaveLoading

![](https://github.com/race604/WaveLoading/blob/master/screenshots/screenshot.gif)

**Comment by brijeshshah13** [comment]
@Dharmik98 We will go with the standard `ProgressBar` as of now.

**Comment by brijeshshah13** [comment]
@Dharmik98 What is the progress of this issue?
