### ISSUE TITLE
Display appropriate message when there are no corresponding repositories

### ISSUE THREAD

**Issue by brijeshshah13** [brijeshshah13/OpenCI#2]
**Actual Behavior**

Displays a Toast message.

**Expected Behavior**

Display an appropriate message on the screen to acknowledge user that they are no repositories in the current tab, i.e., either `Public` or `Private`.

**Steps to reproduce it**

Login in the app.

**Comment by brijeshshah13** [comment]
@harshvardhan-takawale Can you begin with this issue?

**Comment by harshvardhan-takawale** [comment]
@brijeshshah13  Yup I'll get this done.

**Comment by brijeshshah13** [comment]
@harshvardhan-takawale Cool! Also, please think of an image/emoji to complement with the message.
