### ISSUE TITLE
App does not Logout completely [Activity not destroyed]

### ISSUE THREAD

**Issue by antarikshc** [brijeshshah13/OpenCI#29]
- [x] Bug Report
    
### Bug Report    

**Actual Behaviour**

App does not Close Home/Dashboard Activity when 'Logout' button is pressed.
User can go back to the Logged in Home/Dashboard activity by pressing back button.

**Expected Behaviour**

App should release all logged in states and destroy the Home/Dashboard activity.
App should close itself when user presses back button on Login Activity

**Comment by rob729** [comment]
@brijeshshah13 @antarikshc  Can I work on this issue?
